version: '2'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    environment: 
    - MANUL_ADDR=http://manul:3000
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '1'
  
  manul:
    image: vymarkov/manul:0.0.1
    env_file: 
    - ./env/.env
    - ./env/.env.mongo
    environment:
    - DOCKER_HOST=${DOCKER_HOST}
    - DOCKER_CA=${DOCKER_CA}
    - DOCKER_CERT=${DOCKER_CERT}
    - DOCKER_KEY=${DOCKER_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: '5m'
        max-file: '5'
        
  redis:
    image: redis:3-alpine
    logging:
      driver: "json-file"
      options:
        max-size: '5m'
        max-file: '5'
    
  mongo:
    image: vymarkov/mongo:3.2
    env_file:
    - ./env/.env.mongo
    labels:
    - "service=mongo"
    - "replset=rs0"
    logging:
      driver: "json-file"
      options:
        max-size: '5m'
        max-file: '5'
    stop_signal: SIGTERM